
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.phpcustom
    volumes:
    - ./public:/var/www/html
    ports:
    - "8080:80"

  database:
    image: mariadb:10.6.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    platform: linux/amd64
    restart: always
    environment:
      PMA_HOST: database
      PMA_USER: user
      PMA_PASSWORD: userpassword
    ports:
      - "8082:80"
    depends_on:
      - database

volumes:
  db_data: