name: Validate and Deploy

on:
  push:
    branches:
      - main
      - '**'   # Esegui il check HTML su tutti i branch al push

jobs:
  # Job per il deploy su Altervista
  deploy:
    needs: html-validation  # Questo fa in modo che il deploy si esegua solo se la validazione è passata
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'  # Esegui solo sul branch `main`

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to Altervista
        env:
          FTP_USERNAME: ${{ secrets.ALTERVISTA_USERNAME }}
          FTP_PASSWORD: ${{ secrets.ALTERVISTA_PASSWORD }}
        run: |
          echo "Starting deploy to Altervista"
          lftp -u "$FTP_USERNAME","$FTP_PASSWORD" ftp://ftp.altervista.org <<EOF
          mirror -R ./ / # Sincronizza la directory corrente con il server Altervista
          quit
          EOF
