name: Validate and Deploy

on:
  push:
    branches:
      - main
      - feature/pipeline

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install FTP Client
        run: sudo apt-get install -y lftp

      - name: Deploy to Altervista
        env:
          FTP_HOST: ${{ secrets.FTP_HOST }}
          FTP_USERNAME: ${{ secrets.ALTERVISTA_USERNAME }}
          FTP_PASSWORD: ${{ secrets.ALTERVISTA_PASSWORD }}
        run: |
          echo "Starting deploy to Altervista"
          lftp -u "$FTP_USERNAME","$FTP_PASSWORD" "$FTP_HOST" <<EOF
          set ssl:verify-certificate no
          rm -rf /public_html/*
          mirror -R ./public/ /
          quit
          EOF
