name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  validator:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      - name: Validate
        uses: Cyb3r-Jak3/html5validator-action@v7.2.0
        with:
          config: .configs/validate-html-config.yml
      - name: Log failures
        if: failure()
        run: cat log.log > "${GITHUB_STEP_SUMMARY}"

  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: 22
        script: |
          cd ../Progetto-TecWeb
          git pull origin main
          docker-compose up -d --build
